[package]
name = "systray"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@nonpolynomial.com>"]

[target.'cfg(windows)'.dependencies]
winapi="*"
user32-sys="*"
kernel32-sys="*"
libc="*"

[target.'cfg(darwin)'.dependencies]
cocoa="*"

[target.'cfg(linux)'.dependencies]
gdk="*"
