[package]
name = "systray"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@machul.is>"]

[dependencies]
log="*"

[target.'cfg(target_os = "windows")'.dependencies]
winapi={ path = "../winapi-rs/" }
user32-sys={ path = "../winapi-rs/lib/user32/" }
kernel32-sys={ path = "../winapi-rs/lib/kernel32/" }
shell32-sys={ path = "../winapi-rs/lib/shell32/" }
libc="*"

[target.'cfg(target_os = "darwin")'.dependencies]
cocoa="*"

# [target.'cfg(target_os = "linux")'.dependencies]
# gdk="*"
