[package]
name = "systray"
version = "0.1.0"
authors = ["Kyle Machulis <kyle@machul.is>"]

[dependencies]
log = "*"

[target.'cfg(target_os = "windows")'.dependencies]
kernel32-sys = { git = "https://github.com/application-developer-DA/winapi-rs.git", branch = "0.2" }
shell32-sys = { git = "https://github.com/application-developer-DA/winapi-rs.git", branch = "0.2" }
user32-sys = { git = "https://github.com/application-developer-DA/winapi-rs.git", branch = "0.2" }
winapi = { git = "https://github.com/application-developer-DA/winapi-rs.git", branch = "0.2" }

libc = "*"

[target.'cfg(target_os = "macos")'.dependencies]
objc = "*"
cocoa = "*"
core-foundation = "*"
